openapi: 3.0.4
info:
  title: Content Flow API
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
tags:
  - name: Auth
    description: Autenticação
paths:
  /register:
    $ref: "./authentication/register.yaml"
  /login:
    $ref: "./authentication/login.yaml"
  /refresh-access-token:
    $ref: "./authentication/refresh-access-token.yaml"