services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contentflow-api
    env_file:
      - .env
    ports:
      - "${API_PORT}:3000"
    command: sh -c "npm install && npm run dev"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - database

  rabbitmq:
    image: rabbitmq:latest
    container_name: contentflow-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}

  database:
    image: postgres:latest
    container_name: contentflow-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
