#file: noinspection YAMLSchemaValidation
openapi: 3.1.0
info:
  title: Content Flow API
  version: 1.0.0
  description: Content Flow API Documentation
    [Download specification file (YAML)](/api/swagger-bundled.yaml)
servers:
  - url: http://localhost:3000/api
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
tags:
  - name: Auth
    description: Authentication related endpoints
  - name: Google OAuth
    description: Endpoints related to Google OAuth
  - name: Recovery Password
    description: Endpoints related to password recovery
  - name: Plans
    description: Endpoints related to plans
  - name: Subscription
    description: Endpoints related to subscriptions
paths:
  /register:
    $ref: "./docs/swagger/authentication/local/register.yaml"
  /login:
    $ref: "./docs/swagger/authentication/local/login.yaml"
  /refresh-access-token:
    $ref: "./docs/swagger/authentication/local/refresh-access-token.yaml"
  /plans:
    $ref: "./docs/swagger/plans/get-plans.yaml"
  /create-checkout-session:
    $ref: "./docs/swagger/subscription/create-checkout-session.yaml"
  /create-subscriptions:
    $ref: "./docs/swagger/subscription/create-subscription.yaml"
  /cancel-subscription:
    $ref: ./docs/swagger/subscription/cancel-subscription.yaml
  /create-google-auth-url:
    $ref: "./docs/swagger/authentication/oauth-google/create-google-auth-url.yaml"
  /login-oauth-google:
    $ref: "./docs/swagger/authentication/oauth-google/login-oauth-google.yaml"
  /create-recovery-password-token:
    $ref: "./docs/swagger/authentication/recovery-password/create-recovery-password-token.yaml"
  /recovery-password:
    $ref: "./docs/swagger/authentication/recovery-password/recovery-password.yaml"
